version: '3.8'
services:

  client-frontend:
    image: webapplication:0.0.1
    build: ./webapplication/.
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./webapplication:/app

  client-backend:
    image: client:0.0.1
    build:
      context: ./server/.
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/information_system_database_db

  service-db:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 380996120958
    ports:
      - "5432:5432"
    volumes:
      - ./server/infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

    ports:
      - "5050:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data: